name: smart_racket_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.10.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_blue_plus: ^1.34.0
  firebase_core: ^2.24.2
  firebase_database: ^10.4.0

  provider: ^6.1.5+1
  permission_handler: ^12.0.1
  web_socket_channel: ^3.0.3
  fl_chart: ^1.1.1
  uuid: ^4.2.1
  intl: ^0.18.1
  google_fonts: ^6.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/icon/app_icon.png
  # 若你要 Android 12 圓角/自適應 icon 更穩，可以打開下面：
  # android_12:
  #   image_path: assets/icon/app_icon.png
  #   icon_background_color: "#FFFFFF"

flutter:
  uses-material-design: true
  assets:
    - assets/poses/
    - assets/icon/app_icon.png
